export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN FAILURE'

export const GET_USER_DETAIL = 'GET_USER_DETAIL'
export const USER_DETAIL_ERROR = 'USER_DETAIL_ERROR'

export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAILURE = 'GET_ALL_USER_FAILURE'

export const SIGN_OUT = 'SIGN_OUT'

export const FIRST_POST_PROFILE_CREATE_SUCCESS = 'FIRST_POST_PROFILE_CREATE_SUCCESS'
export const FIRST_POST_PROFILE_CREATE_FAILURE = 'FIRST_POST_PROFILE_CREATE_FAILURE'

export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS'
export const POST_UPDATE_FAILURE = 'POST_UPDATE_FAILURE'

